config/routes.rb
Rails.application.routes.draw do
  resources :phone_orders
  resources :static
  get 'order/new'

  root  'static#index'
  match '/delivery',    to: 'static#delivery',      via: 'get'
  match '/payment',     to: 'static#payment',       via: 'get'
  match '/about',       to: 'static#about',         via: 'get'
  # match '/order',       to: 'order#new',            via: 'get'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  validates :name, presence: true, length: { maximum: 100 }
  validates :phone, presence: true, length: { maximum: 16 }
end

app/models/phone_order.rb
class PhoneOrder < ApplicationRecord
  validates :name, presence: true, length: { maximum: 100 }
  validates :phone, presence: true,
            length: { maximum: 16, message: "Номер телефон не может содержать больше 16 цифр" }
end
# message: 'Длина телефона не должна превышать 16 цифр'

app/models/user.rb
class User < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def create
    @phone_order = PhoneOrder.new(phone_order_params)

    respond_to do |format|
      if @phone_order.save
        format.html { redirect_to @phone_order, notice: 'Phone order was successfully created.' }
      else
        format.json { render json: @phone_order.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController


  def new
  end
end

app/controllers/phone_orders_controller.rb
class PhoneOrdersController < ApplicationController
  before_action :set_phone_order, only: [:show, :edit, :update, :destroy]

  # GET /phone_orders
  # GET /phone_orders.json
  def index
    @phone_orders = PhoneOrder.all
  end

  # GET /phone_orders/1
  # GET /phone_orders/1.json
  def show
  end

  # GET /phone_orders/new
  def new
    @phone_order = PhoneOrder.new
  end

  # GET /phone_orders/1/edit
  def edit
  end

  # POST /phone_orders
  # POST /phone_orders.json
  def create
    @phone_order = PhoneOrder.new(phone_order_params)

    respond_to do |format|
      if @phone_order.save
        OrderMailer.order_email(@phone_order).deliver_now
        #mail = Mail.new do
        #  from    'sale@pantashop.ru'
        #  to      'djbm@mail.ru'
        #  subject 'This is a test email'
        #  body    'Test'
        #end
        #mail.to_s
        format.html { redirect_to @phone_order, notice: 'Ваша заявка принята и поставлена в очередь на исполнение.' }
        format.json { render :show, status: :created, location: @phone_order }
      else
        format.html { render :new }
        format.json { render json: @phone_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phone_orders/1
  # PATCH/PUT /phone_orders/1.json
  def update
    respond_to do |format|
      if @phone_order.update(phone_order_params)
        format.html { redirect_to @phone_order, notice: 'Ваша заявка изменена и поставлена в очередь на исполнение.' }
        format.json { render :show, status: :ok, location: @phone_order }
      else
        format.html { render :edit }
        format.json { render json: @phone_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_orders/1
  # DELETE /phone_orders/1.json
  def destroy
    @phone_order.destroy
    respond_to do |format|
      format.html { redirect_to phone_orders_url, notice: 'Phone order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone_order
      @phone_order = PhoneOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_order_params
      params.require(:phone_order).permit(:name, :phone)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  before_action :set_phone_order, only: [:show, :edit, :update, :destroy]
  def index
    @phone_order = PhoneOrder.new
  end

  def delivery
    @phone_order = PhoneOrder.new
  end

  def payment
    @phone_order = PhoneOrder.new
  end

  def about
    @phone_order = PhoneOrder.new
  end

  def create
    @phone_order = PhoneOrder.new(phone_order_params)

    respond_to do |format|
      if @phone_order.save
        format.html { redirect_to @phone_order, notice: 'Заявка успешно добавлена' }
      else
        format.json { render json: @phone_order.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/phone_orders_helper.rb
module PhoneOrdersHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_footer.html.erb
<div class="container footer">
  <div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4"></div>
    <div class="col-lg-4 col-md-4 col-sm-4">
      <h4 class="text-center">Подписывайтесь</h4>
      <div class="social">
        <a href="https://www.facebook.com/groups/pantashopru/" target="_blank"><img src="/images/facebook.svg"></a>
        <!--<a href="#" target="_blank"><img src="/images/twitter.svg"></a>-->
        <a href="https://vk.com/pantashop" target="_blank"><img src="/images/vk.svg"></a>
        <a href="https://ok.ru/group/52981179416709" target="_blank"><img src="/images/ok.svg"></a>
        <!--<a href="#" target="_blank"><img src="/images/instagram.svg"></a>-->
      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4">
      <h4>Способы оплаты</h4>
      <div class="change-pay">
        <a href="#" target="_blank"><img src="/images/Visa-dark.svg"></a>
        <a href="#" target="_blank"><img src="/images/MasterCard-dark.svg"></a>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-4 col-md-4 col-sm-5 partners">
      По вопросам сотрудничества:<br>
      <a href="mailto:sale@pantashop.ru">sale@pantashop.ru</a>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 text-center copyright">
      ООО «Маркет-Трейд» 659322, Алтайский край г. Бийск ул. Декабристов д. 33 кв. 25. ОГРН:1162225053935
      <br>
      <span class="copy-white">© 2016 Pantashop</span>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-3"></div>
  </div>
</div>

</body>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Pantashop - высококачественный пантогематоген</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,500i,700,700i&amp;subset=cyrillic,cyrillic-ext" rel="stylesheet">
  <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/manifest.json">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>

  <![endif]-->
</head>
<body>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle navbar-left" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><img src="/images/logotype.svg" width="42" height="42"> <img src="/images/Pantashop.svg" width="111" height="20"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Каталог <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><a href="#">Действие</a></li>
                <li><a href="#">Другое действие</a></li>
                <li><a href="#">Что-то еще</a></li>
                <li class="divider"></li>
                <li><a href="#">Отдельная ссылка</a></li>
                <li class="divider"></li>
                <li><a href="#">Еще одна отдельная ссылка</a></li>
            </ul>
        </li>-->
        <li><%= link_to "Доставка",    '/delivery' %></li>
        <li><%= link_to "Оплата",    '/payment' %></li>
        <li><%= link_to "О компании",    '/about' %></li>
      </ul>

      <div class="navbar-form navbar-right col-lg-offset-1">
        <button type="submit" class="btn btn-default callback" data-toggle="modal" data-target="#myModal">Заказать звонок</button>
      </div>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/_modal_phone_order.html.erb
<!--Блок модальное окна Заказать звонок-->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Оформление заказа</h4>
      </div>
      <div class="modal-body">

        <%= form_for(@phone_order) do |f| %>

            <div class="field  input-group-lg">
              <%= f.label 'Имя' %>
              <%= f.text_field :name, :class => 'form-control', :placeholder => 'Иван Иванов' %>
            </div>

            <div class="field  input-group-lg">
              <%= f.label 'Ваш телефон' %>
              <%= f.telephone_field :phone, :class => 'form-control', :placeholder => '+7 (9--) --- -- --' %>
            </div>

            <div class="actions">
              <%= f.submit 'Оформить заказ', :class => 'btn btn-lg btn-success' %>
            </div>
        <% end %>

      </div>

    </div>
  </div>
</div>
<!--Конец блока-->

app/views/layouts/application.html.erb
<%= render 'layouts/header' %>
<%= render 'layouts/menu' %>
<%= yield %>
<%= render 'layouts/footer' %>

app/views/order/new.html.erb
<h1>Order#new</h1>
<p>Find me in app/views/order/new.html.erb</p>

app/views/phone_orders/_form.html.erb
<%= form_for(phone_order) do |f| %>
  <% if phone_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(phone_order.errors.count, "error") %> prohibited this phone_order from being saved:</h2>

      <ul>
      <% phone_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phone_orders/edit.html.erb
<div class="container content simple-page">
<h1>Editing Phone Order</h1>

<%= render 'form', phone_order: @phone_order %>

<%= link_to 'Show', @phone_order %> |
<%= link_to 'Back', phone_orders_path %>
</div>

app/views/phone_orders/index.html.erb
<div class="container content simple-page">
<p id="notice"><%= notice %></p>

<h1>Phone Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phone_orders.each do |phone_order| %>
      <tr>
        <td><%= phone_order.name %></td>
        <td><%= phone_order.phone %></td>
        <td><%= link_to 'Show', phone_order %></td>
        <td><%= link_to 'Edit', edit_phone_order_path(phone_order) %></td>
        <td><%= link_to 'Destroy', phone_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Phone Order', new_phone_order_path %>
</div>

app/views/phone_orders/new.html.erb
<div class="container content simple-page">
<h1>New Phone Order</h1>

<%= render 'form', phone_order: @phone_order %>

<%= link_to 'Back', phone_orders_path %>
</div>

app/views/phone_orders/show.html.erb
<div class="container content simple-page">
  <h1>Спасибо!</h1>
  <div class="alert alert-info" role="alert"><%= notice %></div>

  <div class="alert alert-success" role="alert">
   Уважаемый(ая), <%= @phone_order.name %>.<br>
   В течении 10-20 минут с Вами свяжется наш менеджер<br>
   по указаному номеру <strong><%= @phone_order.phone %></strong>
</div>
<div class="text-center"><a href="/">Вернуться</a></div>

</div>